version: "3"

services:

  webdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: webdev
    container_name: webdev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: npm run start

volumes:
  node_modules:
